Repository prgrms-web-devcourse-final-project/WEB1_2_TenPaws_FE, pull requests merged in 2024-11, with the labels that each got.

#12 chore: 깃허브 리뷰어 제한(#12)
  .github/CODEOWNERS
Labels: 환경설정

#14 design: 헤더 퍼블리싱 작업(#14)
  public/side.svg
  src/components/Header.tsx
Labels: 퍼블리싱

#26 Design/matching/#5
  package-lock.json
  package.json
  postcss.config.js
  src/App.tsx
  src/assets/image/mainimage.webp
  src/assets/image/pu.avif
  src/main.tsx
  src/pages/matching/MatchingPage.tsx
  src/router.tsx
  tailwind.config.js
Labels: 퍼블리싱

#28 Design/detail page/#15
  src/App.tsx
  src/pages/matching/DetailPage.tsx
  src/pages/matching/MatchingPage.tsx
  src/router.tsx
Labels: 퍼블리싱

#31 상세정보 수정 페이지
  src/App.tsx
  src/pages/matching/DetailCorrect.tsx
  src/pages/matching/DetailReadPage.tsx
Labels: 퍼블리싱

#36 마이페이지 (유저) 퍼블리싱
  src/App.tsx
  src/assets/image/bar.png
  src/assets/image/check.png
  src/assets/image/complete.png
  src/assets/image/matching.png
  src/components/MyPageModal.tsx
  src/pages/my/MyPageUser.tsx
  tailwind.config.js
Labels: 퍼블리싱

#33 선호 동물 등록 페이지
  src/App.tsx
  src/pages/Preferences.tsx
  src/pages/matching/PreferPage.tsx
Labels: 퍼블리싱

#24 design: 로그인 퍼블리싱 작업
  src/App.tsx
  src/pages/CreateUser2.tsx
  src/pages/Login.tsx
Labels: 퍼블리싱

#38 design: 회원가입 페이지 퍼블리싱
  src/pages/Signup.tsx
Labels: 퍼블리싱

#40 마이페이지 보호소
  src/App.tsx
  src/pages/matching/DetailCorrect.tsx
  src/pages/matching/DetailPage.tsx
  src/pages/matching/DetailReadPage.tsx
  src/pages/matching/MatchingPage.tsx
  src/pages/matching/PreferPage.tsx
  src/pages/my/MyPageShelter.tsx
  src/pages/my/MyPageUser.tsx
Labels: 퍼블리싱

#42 Design/bar/#10
  src/App.tsx
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
Labels: 퍼블리싱

#45 feature: 헤더 기능 구현
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
Labels: 기능구현

#46 보호소 주소 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/assets/image/check.png
  src/assets/image/complete.png
  src/pages/matching/DetailPage.tsx
  src/pages/matching/DetailReadPage.tsx
  src/pages/matching/MatchingPage.tsx
  src/pages/matching/PreferPage.tsx
  src/pages/my/MyPageShelter.tsx
  src/pages/my/MyPageUser.tsx
  src/pages/my/ShelterAddress.tsx
  tailwind.config.js
Labels: 퍼블리싱

#50 feature: 헤더 기능 구현 완료(+사이드바)(#21)
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
  src/pages/Login.tsx
Labels: 기능구현

#51 입양신청페이지 퍼블리싱
  src/App.tsx
  src/pages/my/AdoptionList.tsx
  src/pages/my/MyPageShelter.tsx
Labels: 퍼블리싱

#54 [design] 알림 페이지 퍼블리싱
  src/pages/Alarm.tsx
Labels: 퍼블리싱

#53 design: Ai 매칭 페이지 퍼블리싱
  src/App.tsx
  src/pages/AIMatching.tsx
Labels: 퍼블리싱

#55 Design/error/#52
  src/App.tsx
  src/pages/Error.tsx
  src/pages/my/MyPageShelter.tsx
Labels: 퍼블리싱

#56 이상형 월드컵 페이지 퍼블리싱, 기능 구현
  src/App.tsx
  src/pages/guide/Announcementpostcreate.tsx
  src/pages/guide/QAandApostcreate.tsx
  src/pages/worldcup/Worldcup.tsx
Labels: 퍼블리싱, 기능구현
