Repository prgrms-web-devcourse-final-project/WEB1_2_TenPaws_FE, pull requests merged in 2024-12, with the labels that each got.

#59 Feature/mypage user/#57
  package-lock.json
  package.json
  src/pages/Error.tsx
  src/pages/matching/DetailCorrect.tsx
  src/pages/matching/DetailPage.tsx
  src/pages/my/AdoptionList.tsx
  src/pages/my/MyPageShelter.tsx
  src/pages/my/MyPageUser.tsx
  src/pages/my/ShelterAddress.tsx
Labels: 퍼블리싱, 기능구현

#61 design: 메인 페이지 퍼블리싱
  src/App.tsx
  src/pages/Main.tsx
Labels: 퍼블리싱

#62 feature: 헤더 기능 구현(사이드바 + 드롭다운바)
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
Labels: 기능구현

#63 feature: 회원가입 페이지(유저 및 보호소) 기능 구현
  src/pages/CreateUser1.tsx
  src/pages/CreateUser2.tsx
  src/pages/Signup.tsx
  src/utils/axiosInstance.ts
Labels: 기능구현

#64 feature: 푸터 기능 구현
  src/components/Footer.tsx
  src/utils/axiosInstance.ts
Labels: 기능구현

#65 마이페이지, 매칭 페이지 기능구현
  src/pages/matching/DetailCorrect.tsx
  src/pages/matching/DetailPage.tsx
  src/pages/matching/PreferPage.tsx
  src/pages/my/AdoptionList.tsx
  src/pages/my/MyPageShelter.tsx
  src/pages/my/MyPageUser.tsx
  src/pages/my/ShelterAddress.tsx
  tailwind.config.js
Labels: 기능구현

#67 FAQ / 문의 답변 기능 완성
  src/components/Chat.tsx
  src/components/FAQ.tsx
  src/components/FAQEdIt.tsx
  src/components/GuideNavigation.tsx
  src/components/GuideNavigationMap.tsx
  src/pages/guide/Announcement.tsx
  src/pages/guide/AnnouncementEdit.tsx
  src/pages/guide/Announcementpost.tsx
  src/pages/guide/Announcementpostcreate.tsx
  src/pages/guide/QAandApost.tsx
  src/pages/guide/QAandApostcreate.tsx
  src/pages/guide/QAndA.tsx
  src/pages/guide/QAndAEdit.tsx
  src/pages/guide/QandAcommentcreate copy.tsx
  src/pages/guide/QandAcommentcreateEdit.tsx
Labels: 기능구현

#68 Feature/header/#21
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
  src/utils/axiosInstance.ts
Labels: 기능구현

#70 feature: 메인 페이지 기능 구현
  src/pages/Main.tsx
Labels: 퍼블리싱, 기능구현

#71 feature: 유저정보 생성 페이지 기능 수정
  src/pages/CreateUser1.tsx
  src/pages/CreateUser2.tsx
Labels: 기능구현

#73 feature: footer 기능 구현
  src/components/Footer.tsx
Labels: 기능구현

#75 feature: 회원가입 최종 구현 완료
  src/pages/CreateUser1.tsx
  src/pages/CreateUser2.tsx
Labels: 기능구현

#76 feature: ai 매칭 기능 구현
  src/components/Footer.tsx
  src/pages/AIMatching.tsx
Labels: 기능구현

#78 feature: login 기능 구현 최종
  src/pages/Login.tsx
Labels: 기능구현

#79 feature: 헤더 기능 구현 최종
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
Labels: 기능구현

#80 feature: alarm 기능 구현 최종
  src/pages/Alarm.tsx
Labels: 기능구현

#82 feature: 회원가입 페이지 연결 url 수정
  src/pages/CreateUser1.tsx
  src/pages/CreateUser2.tsx
Labels: 기능구현

#81 채팅 퍼블리싱 완성
  src/components/Chat.tsx
  src/components/FAQ.tsx
  src/pages/guide/Announcement.tsx
  src/pages/guide/Announcementpostcreate.tsx
Labels: 퍼블리싱

#84 기능 구현 및 수정
  src/App.tsx
  src/components/Header.tsx
  src/pages/matching/DetailCorrect.tsx
  src/pages/matching/DetailPage.tsx
  src/pages/matching/DetailReadPage.tsx
  src/pages/matching/MatchingPage.tsx
  src/pages/matching/PreferPage.tsx
  src/pages/my/AdoptionList.tsx
  src/pages/my/MyPageShelter.tsx
  src/pages/my/MyPageUser.tsx
  src/pages/my/ShelterAddress.tsx
Labels: 기능구현

#83 feature: ai-matching 기능 구현 수정
  src/pages/AIMatching.tsx
Labels: 기능구현

#87 Feature/alarm/#22
  src/pages/Alarm.tsx
Labels: 기능구현

#88 Feature/social/#49
  src/App.tsx
  src/components/Header.tsx
  src/pages/AuthResponse.tsx
  src/pages/Login.tsx
  src/pages/sociallogin/KakaoLogin.ts
  src/pages/sociallogin/NaverLogin.ts
Labels: 기능구현

#89 Feature/social/#49
  index.html
  src/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
  src/global.d.ts
  src/pages/AuthResponse.tsx
  src/pages/Login.tsx
  src/pages/sociallogin/KakaoLogin.ts
  src/pages/sociallogin/NaverLogin.ts
  src/utils/axiosInstance.ts
Labels: 기능구현

#95 오류 수정
  package-lock.json
  src/App.tsx
  src/pages/Error.tsx
  src/pages/matching/DetailPage.tsx
  src/pages/matching/DetailReadPage.tsx
  src/pages/matching/MatchingPage.tsx
  src/pages/matching/PreferPage.tsx
  src/pages/my/AdoptionList.tsx
  src/pages/my/MyPageShelter.tsx
  src/pages/my/MyPageUser.tsx
  src/pages/my/ShelterAddress.tsx
Labels: 오류수정

#92 Update Login.tsx
  src/pages/Login.tsx
Labels: 기능구현

#93 feature: 알림 기능 구현 수정
  src/pages/Alarm.tsx
Labels: 기능구현

#94 feature: 매칭 페이지 알림 문구 수정(+ 퍼블리싱 약간 수정)
  src/pages/AIMatching.tsx
Labels: 퍼블리싱, 기능구현

#97 Feature/alarm/#22
  src/pages/Alarm.tsx
Labels: 기능구현

#99 오류 수정 코드
  package-lock.json
  src/pages/guide/QAandApostcreate.tsx
  src/pages/matching/DetailPage.tsx
  src/pages/matching/DetailReadPage.tsx
  src/pages/matching/MatchingPage.tsx
  src/pages/matching/PreferPage.tsx
  src/pages/my/AdoptionList.tsx
  src/pages/my/MyPageShelter.tsx
  src/pages/my/MyPageUser.tsx
  src/pages/my/ShelterAddress.tsx
Labels: 오류수정

#100 오류 해결
  package-lock.json
  src/assets/page4.png
  src/pages/AIMatching.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
Labels: 퍼블리싱, 오류수정

#102 상세정보 수정 페이지
  src/App.tsx
  src/pages/matching/DetailCorrect.tsx
  src/pages/matching/DetailPage.tsx
  src/pages/matching/DetailReadPage.tsx
  src/pages/matching/MatchingPage.tsx
  src/pages/my/MyPageShelter.tsx
  src/pages/my/MyPageUser.tsx
Labels: 기능구현

#104 fix: 메인 페이지 수정
  src/assets/page2.png
  src/assets/page3.png
  src/pages/Main.tsx
Labels: 퍼블리싱, 기능구현

#105 매칭 페이지 퍼블리싱 및 기능 수정
  src/pages/matching/DetailPage.tsx
  src/pages/matching/DetailReadPage.tsx
  src/pages/matching/MatchingPage.tsx
  src/pages/matching/PreferPage.tsx
  src/pages/my/MyPageShelter.tsx
  src/pages/my/MyPageUser.tsx
  src/pages/my/ShelterAddress.tsx
  tailwind.config.js
Labels: 퍼블리싱

#106 design: 메인 페이지 사진 변경
  page4.png
  src/assets/page.png
  src/assets/page2.png
  src/assets/page4.png
  src/pages/Main.tsx
Labels: 퍼블리싱

#107 design: 헤더 추가(반려동물 등록)
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
Labels: 퍼블리싱, 기능구현

#108 feature: 이메일 메세지 변경
  src/pages/CreateUser1.tsx
  src/pages/CreateUser2.tsx
Labels: 퍼블리싱, 기능구현

#109 Feature/ai/#23
  src/pages/AIMatching.tsx
Labels: 퍼블리싱, 기능구현

#110 feature: 아이콘 확대 효과 추가
  src/pages/Main.tsx
Labels: 기능구현
